rate_hz: 30.0

min_velocity: 0.2
max_velocity: 0.5

head_timer: 1.0
target_pose_watchdog_time_s: 3.0
wait_closer_timeout: 10.0
wait_arriving_time: 5.0
P_multiplier: 0.1

desired_distance: 1.0
z_height: 1.15
warning_distance: 1.7
error_distance: 2.1
destination_max_distance: 0.5

max_action_retries: 0
